print('Enter the first number to add: ')
first = int(input())
print('Enter the second number to add: ')
second = int(input())
print('Enter the third number to add: ')
third = int(input())
print('The sum is\t' + str(first + second + third) + '\n')
